# Generated by Django 6.1.1 on 2026-09-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="photo",
            field=models.ImageField(upload_to="userphoto/"),
        ),
    ]
