# Generated by Django 6.1.1 on 2026-09-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_alter_customer_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
    ]
