# Generated by Django 6.1.1 on 2026-09-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="productphoto/")),
                ("description", models.TextField()),
            ],
        ),
    ]
