# Generated by Django 6.1.1 on 2026-09-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_email", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("photo", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
    ]
