# Generated by Django 6.1.1 on 2026-09-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_product_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_order",
            name="qnty",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
