# Generated by Django 6.1.1 on 2026-09-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_product_order_qnty"),
    ]

    operations = [
        migrations.CreateModel(
            name="help",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("customer_email", models.EmailField(max_length=254, unique=True)),
                ("query", models.CharField(max_length=100)),
                ("customer_reply", models.TextField()),
                ("admin_reply", models.TextField()),
            ],
        ),
    ]
