# Generated by Django 6.1.1 on 2026-09-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="help",
            name="customer_email",
            field=models.EmailField(max_length=100),
        ),
    ]
